Fix Unit Tests
CLMBRs/ultk pull request #49
Opened 2024-11-20 03:38 UTC by Ashvin-Ranjan

- This should fix all of the tests in the `src/tests` directory, which are currently broken (as mentioned in #48)
- There also may be changes to other classes such as `Universe` and `Meaning`

### Notes
- These tests will still not work until #47 is merged, since the issue that fixes blocks the use of the `ultk` package entirely.

2024-11-20 03:45 UTC, Ashvin-Ranjan commented
I have currently left this as a draft because there are a few issues which I wanted to get some clarification on before I think this is ok to merge.

The first is that it appears that there used to be some old functionality with `Universe` where if only a tuple of `Referent`s were passed in, then the `prior` tuple would be generated automatically to be a uniform distribution. This seemed to be removed when `@dataclass(frozen=True)` was added to `Universe`. I have added this functionality back by creating a constructor that uses `object.__set_attr__` but if this is too big of a change or unwanted this could be reverted.

The second is that I am unable to currently fix the test `test_meaning_subset` in `test_semantics.py` because it tests a functionality of `Meaning` which appears to have been removed where when `Meaning.__init__` was called it would check to see that all `Referent`s passed in were also contained in the `Universe`. I am wondering if this should be re-implemented or if the test should be deleted.

Finally, for `test_language_degree` in `test_language.py`, I have rewritten the `isAnimal` function, but I am unsure if the current functionality of the test actually tests what it is supposed to.

2024-12-02 20:21 UTC, shanest requested changes
Thanks, Ash, great stuff!  A couple small things here and there.  And for the third/final question: `isAnimal`/degree_property looks good to me

2024-12-02 20:43 UTC, Ashvin-Ranjan commented on src/ultk/language/semantics.py
> +            prior[:] if prior is not None else (1.0/len(referents) for _ in referents)
Thank you for pointing out the issue with the tuple needing `tuple` before it. I have tested `prior or tuple(1 / len(referents) for _ in referents)` and it does work, so I have used that instead.

2024-12-02 20:44 UTC, shanest approved these changes
Awesome, thanks Ash!

2024-12-02 20:44 UTC, merged